for multiple breadcrumbs
naotoomura/breadcrumbs_on_rails pull request #1
Opened 2019-09-24 08:52 UTC by naotoomura

とりあえず書いてみた感じ

2019-09-24 19:21 UTC, necojackarc requested changes
```ruby
    add_breadcrumb "String", "/"
    add_breadcrumb "Hoge", "/hoge/"
    add_breadcrumb "Me", "/hoge/moge"

    next_breadcrumbs

    add_breadcrumb "String", "/"
    add_breadcrumb "Moge", "/moge/"
    add_breadcrumb "You", "/hoge/moge"
```

というインターフェース、後方互換性もあり、悪くなさそうです！

と、思ったのですが、チャットで指摘があった、

> controller内でadd_breadcrumbしていて、さらに個々のaction内でadd_breadcrumbした時の挙動が自明ではない

という点、なかなか良い点をついてるかなと思いました。
複数のパンくずリストがある場合、それぞれに何らかのネームスペースを提供できると良いかなと思いました。ネームスペースなしだと、`default` が使われ、後方互換性が保たれる、のようなイメージです。

```ruby
    add_breadcrumb "String", "/"
    add_breadcrumb "Hoge", "/hoge/"
    add_breadcrumb "Me", "/hoge/moge"

    add_breadcrumb "String", "/", { group_name: "sub" }
    add_breadcrumb "Moge", "/moge/",  { group_name: "sub" }
    add_breadcrumb "You", "/hoge/moge" { group_name: "sub" }
```

とか、

```ruby
    add_breadcrumb "String", "/"
    add_breadcrumb "Hoge", "/hoge/"
    add_breadcrumb "Me", "/hoge/moge"

    add_breadcrumns "sub" do |breadcrumns|
      add_breadcrumb "String", "/"
      add_breadcrumb "Moge", "/moge/"
      add_breadcrumb "You", "/hoge/moge"
    end
```

とか、でしょうか？

2019-09-24 19:21 UTC, necojackarc commented on lib/breadcrumbs_on_rails/action_controller.rb
> +      self.breadcrumbs_list.last
[IMO]
なぜ `last` を取るのかの説明はあったほうが良さそうです。

2019-09-24 19:21 UTC, necojackarc commented on lib/breadcrumbs_on_rails/action_controller.rb
> +    def next_breadcrumbs_list
[MUST]
```suggestion
    def next_breadcrumbs
```

の間違いでしょうか？ `breadcrumbs_list` が配列の配列だと思うので、ここでは次の配列 (breadcrumns) に移るの意味だと思います。

2019-09-26 02:48 UTC, naotoomura commented
@necojackarc 
ネームスペースを提供するアイデアは「後から特定のパンくずリストに要素を足せるようになる」という点に於いて良いと思います！

でも、パンくずリストを複数出すという要件において、パンくずリストの順番(の管理)は必須なので、
`next_breadcrumbs`のオプションで名前をつけられ、`add_breadcrumb`のオプションで名前を指定できる、といった感じはどうでしょう？

同名の breadcrumbs が作られようとした時はどうするべきか、というのはちょっとあります。(できればwarningを出して)breadcrumbsを作らない、って方向かなと思ってます

2019-09-26 08:36 UTC, naotoomura commented
名前をつけるのはどうもシンプルじゃない気がして、「特定のパンくずリストに要素を足せるようになる」ようにするのは index 指定で対応してみました

2019-09-26 19:21 UTC, necojackarc reviewed
かなり良さそうです！が、気になるところがあったのでいくつかコメントしました！

2019-09-26 19:21 UTC, necojackarc commented on README.md
> +### Multiple breadcrumns
```suggestion
### Multiple breadcrumbs
```

2019-09-26 19:21 UTC, necojackarc commented on README.md
> +For using multiple breadcrumbs, call `next_breadcrumbs` to create new breadcrumb stack.
```suggestion
For using multiple breadcrumbs, call `next_breadcrumbs` to create a new breadcrumb stack.
```

2019-09-26 19:21 UTC, necojackarc commented on README.md
> +The `add_breadcrumb` method understands all options you are used to pass to a Rails controller filter. In fact, behind the scenes this method uses a `before_filter` to store the tab in the `@breadcru
ここに `@breadcrumbs_list` と明記されているということは、`@breadcrumbs` はパブリックに使われてる可能性もあるかもしれませんね……そうだった場合、`@breadcrumbs_list` から `@breadcrumbs` は受け入れてもらえない可能性がありそうですね……。

後方互換性を残すために、`@breadcrumbs` には `@breadcrumbs_list.last` を常にもたせとく、などの対応が必要かもしれません。

2019-09-26 19:21 UTC, necojackarc commented on README.md
> +When after create new breadcrumb stack, if you want to push to an existing stack.
```suggestion
You can push a new element to an arbitrary stack by specifying an `index` option.
```

とかでしょうか？

2019-09-26 19:21 UTC, necojackarc commented on test/views/example/default.html.erb
> +<%= render_breadcrumbs(list_separator: "|") %>
この変更はなんのために必要なのでしょうか？

2019-09-27 05:56 UTC, naotoomura commented on test/views/example/default.html.erb
> +<%= render_breadcrumbs(list_separator: "|") %>
`list_separator` の使い方を test で示しておく必要があると思いました

2019-09-29 10:59 UTC, necojackarc approved these changes

2019-09-29 10:59 UTC, necojackarc commented on README.md
> +The `add_breadcrumb` method understands all options you are used to pass to a Rails controller filter. In fact, behind the scenes this method uses a `before_filter` to store the tab in the `@breadcru
```suggestion
The `add_breadcrumb` method understands all options you are used to pass to a Rails controller filter. In fact, behind the scenes this method uses a `before_filter` to store the tab in the `@breadcrumbs` and `@breadcrumbs_list` variables.
```

2019-09-30 02:24 UTC, merged